twinstall: Force variable type
Force the usage of variable type since it is different on the 32-bit
devices. Use this commit to avoid the problem.

bugs:
bootable/recovery/twinstall.cpp:201:67: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'long long' [-Werror,-Wformat]
LOGINFO("has_legacy_properties: mmap (size=%zu) failed: %s!\n", finfo.st_size, strerror(errno));
                                           ~~~                  ^~~~~~~~~~~~~
                                           %lld

Change-Id: Ie0c51a90490e0c069fff33884a9431a97361f5c6